# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Maintenence'), ('o', 'On Loan'), ('a', 'Avaliable'), ('r', 'Reserved')], default='d', help_text='Book avaliability', max_length=1),
        ),
    ]
